CREATE TABLE mytable(
   id int AUTO_INCREMENT NOT NULL PRIMARY KEY
  ,Position VARCHAR(10) NOT NULL 
  ,Player   VARCHAR(22) NOT NULL 
  ,Club     VARCHAR(23) NOT NULL
  ,Age      INTEGER  NOT NULL
  ,Caps     INTEGER  NOT NULL
);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Goalkeeper','Franco Armani','River Plate (ARG)',36,18);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Goalkeeper','Emiliano Martinez','Aston Villa (ENG)',30,19);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Goalkeeper','Geronimo Rulli','Villarreal (SPA)',30,4);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Marcos Acuna','Sevilla (SPA)',30,43);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Juan Foyth','Villarreal (SPA)',24,16);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Lisandro Martinez','Man United (ENG)',24,10);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Nahuel Molina','Atletico Madrid (SPA)',24,19);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Gonzalo Montiel','Sevilla (SPA)',25,19);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Nicolas Otamendi','Benfica (POR)',34,93);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','German Pezzella','Real Betis (SPA)',31,32);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Cristian Romero','Tottenham (ENG)',24,12);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Nicolas Tagliafico','Lyon (FRA)',30,42);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Midfielder','Rodrigo De Paul','Atletico Madrid (SPA)',28,44);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Midfielder','Enzo Fernandez','Benfica (POR)',21,3);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Midfielder','Alejandro ''Papu'' Gomez','Sevilla (SPA)',34,15);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Midfielder','Alexis Mac Allister','Brighton (ENG)',23,8);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Midfielder','Exequiel Palacios','Bayer Leverkusen (GER)',24,20);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Midfielder','Leandro Paredes','Juventus (ITA)',28,46);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Midfielder','Guido Rodriguez','Real Betis (SPA)',28,26);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Forward','Julian Alvarez','Man City (ENG)',22,12);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Forward','Thiago Almada**','Atlanta United (USA)',21,1);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Forward','Angel Di Maria','Juventus (ITA)',34,124);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Forward','Paulo Dybala','AS Roma (ITA)',28,34);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Forward','Angel Correa*','Atletico Madrid',25,22);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Forward','Lautaro Martinez','Inter Milan (ITA)',25,40);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Forward','Lionel Messi','PSG (FRA)',35,165);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Goalkeeper','Alisson','Liverpool (ENG)',30,56);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Goalkeeper','Ederson','Manchester City (ENG)',29,18);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Goalkeeper','Weverton','Palmeiras (BRA)',34,11);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Marquinhos','PSG (FRA)',28,70);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Eder Militao','Real Madrid (SPA)',24,23);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Thiago Silva','Chelsea (ENG)',38,108);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Danilo','Juventus (ITA)',24,15);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Alex Telles','Sevilla (SPA)',29,7);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Dani Alves','Pumas UNAM (MEX)',39,125);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Alex Sandro','Juventus (ITA)',31,37);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Bremer','Juventus (ITA)',25,1);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Midfielder','Fabinho','Liverpool (ENG)',28,28);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Midfielder','Casemiro','Manchester United (ENG)',30,64);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Midfielder','Bruno Guimaraes','Newcastle United (ENG)',24,8);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Midfielder','Fred','Manchester United (ENG)',29,27);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Midfielder','Lucas Paqueta','West Ham (ENG)',25,34);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Midfielder','Everton Ribeiro','Flamengo (BRA)',33,22);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Forward','Gabriel Martinelli','Arsenal (ENG)',21,3);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Forward','Vinicius Jr.','Real Madrid (SPA)',22,15);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Forward','Neymar','PSG (FRA)',30,120);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Forward','Antony','Manchester United (ENG)',22,10);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Forward','Rodrygo','Real Madrid (SPA)',21,6);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Forward','Raphinha','Barcelona (SPA)',25,10);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Forward','Richarlison','Tottenham (ENG)',25,37);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Forward','Pedro','Flamengo (BRA)',25,2);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Forward','Gabriel Jesus','Arsenal (ENG)',25,56);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Goalkeeper','Alphonse Areola','West Ham (ENG)',29,5);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Goalkeeper','Hugo Lloris','Tottenham (ENG)',35,139);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Goalkeeper','Steve Mandanda','Rennes (FRA)',37,34);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Axel Disasi','Monaco (FRA)',24,0);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Lucas Hernandez*','Bayern Munich (FRA)',26,32);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Theo Hernandez','AC Milan (ITA)',25,7);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Ibrahima Konate','Liverpool (ENG)',23,2);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Jules Kounde','Barcelona (SPA)',23,12);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Benjamin Pavard','Bayern Munich (GER)',26,46);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','William Saliba','Arsenal (ENG)',21,7);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Dayot Upamecano','Bayern Munich (GER)',23,7);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Defender','Raphael Varane','Manchester United (ENG)',29,87);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Midfielder','Eduardo Camavinga','Real Madrid (SPA)',19,4);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Midfielder','Youssouf Fofana','AS Monaco (FRA)',23,2);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Midfielder','Matteo Guendouzi','Marseille (FRA)',23,6);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Midfielder','Adrien Rabiot','Juventus (ITA)',27,29);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Midfielder','Aurelien Tchouameni','Real Madrid (SPA)',22,14);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Midfielder','Jordan Veretout','Marseille (FRA)',29,5);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Forward','Ousmane Dembele','Barcelona (FRA)',25,28);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Forward','Kingsley Coman','Bayern Munich (GER)',26,40);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Forward','Olivier Giroud','AC Milan (ITA)',36,114);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Forward','Antoine Griezmann','Atletico Madrid (SPA)',31,110);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Forward','Kylian Mbappe','PSG (FRA)',23,59);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Forward','Marcus Thuram','Bor. M''Gladbach (GER)',25,4);
INSERT INTO mytable(Position,Player,Club,Age,Caps) VALUES ('Forward','Randal Kolo Muani','Monaco (FRA)',23,2);  